baseURL = "https://craftingcode.dev"
defaultContentLanguage = "es"

enableRobotsTXT = true
summaryLength = 0

googleAnalytics = "G-XL5G4KP0XD"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pageSize=10
